### ISSUE TITLE
Crash when creating entity model

### ISSUE THREAD

**Issue by Herobattler** [Viola-Siemens/Villager-Armor-Layer#1]
[crash-2023-04-05_09.49.49-client.txt](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/11156462/crash-2023-04-05_09.49.49-client.txt)

**Comment by Viola-Siemens** [comment]
Please upload debug.log or latest.log. And any other mods you also installed?

**Comment by Herobattler** [comment]
[mods.txt](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/11157842/mods.txt)
[debug.log](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/11157846/debug.log)
[latest.log](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/11157847/latest.log)

**Comment by Viola-Siemens** [comment]
wait, you are not playing game with villager armor mod? i cannot find it in your mods.txt and debug.log

**Comment by Herobattler** [comment]
oops wrong log, right one coming up

**Comment by Herobattler** [comment]
[mods.txt](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/11161802/mods.txt)
[latest.log](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/11161787/latest.log)
[debug.log](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/11161788/debug.log)

**Comment by Viola-Siemens** [comment]
See line 8366 in your debug.log, it looks like macawsbridgesbop causes the crash. Forge failed to create mod instance, then it froze the registry.
