### ISSUE TITLE
Does not appear to work in Fabric 1.20.1

### ISSUE THREAD

**Issue by Jim3535** [Viola-Siemens/Villager-Armor-Layer#2]
I tried using this mod with my main game instance and it didn't show the armor layers. So, I tried running it with minimal mods in a test instance and I still don't see armor on villagers. They all look normal.

[latest.log](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/13197166/latest.log)

**Comment by Viola-Siemens** [comment]
Uninstall "Mod Menu" mod will fix it. I don't think the icon of a mod "must be square icon" - maybe you should probably open a issue to that mod.

**Comment by Jim3535** [comment]
Uninstalling mod menu did not fix it.

![2023-10-29_18 24 06](https://github.com/Viola-Siemens/Villager-Armor-Layer/assets/120746893/d7139725-b235-4072-8a00-7dcbdb75ec12)

[latest.log](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/13199897/latest.log)

**Comment by Viola-Siemens** [comment]
I can't see what's going wrong. Does it render villagers' armor successfully after using dispensers to equip them?

**Comment by Viola-Siemens** [comment]
> Is there some other mod required to make them wear armor?

Yes, this mod is client only for rendering the armor layer of villagers, illagers and some other mobs. If you want them wear armors when spawn or by manually giving them armor item, you might looking forward to a certain server-side mod.
