### ISSUE TITLE
Armor trim does not appear on villagers and illagers

### ISSUE THREAD

**Issue by 256smash** [Viola-Siemens/Villager-Armor-Layer#3]
I would like to see the villagers and illagers decorated and fashionable, but their armor trims are not displayed in the game when they are wearing armor with the required trim. I play on version 1.20.1, mod version 5.0.0. Perhaps this is due to rendering.

**Comment by Viola-Siemens** [comment]
Forge or Fabric? What kind of method did you use to put armors on villagers and illagers, dispenser or summon with nbt?

**Comment by 256smash** [comment]
I used the /item command to equip the armor.
It didn't work in both Forge and Fabric.

**Comment by Viola-Siemens** [comment]
Any other mods/resourcepacks are you using? Is it working with optifine?

**Comment by 256smash** [comment]
When I install Optifine on Forge even without this armor mod, it crashes. :(
Minecraft runs on TLauncher for me, I can’t find out the reason for the crash.
The client works well on Fabric.
But here is a list of mods that are installed on Fabric:
Earth2Java
Illager Invasion
Headed
PuzzlesLib
Cloth Config
Architecture
Forge Config API Port
Mod Menu

**Comment by 256smash** [comment]
![1](https://github.com/Viola-Siemens/Villager-Armor-Layer/assets/56295558/de668ba8-f091-4812-97bc-10de87272ece)

**Comment by Viola-Siemens** [comment]
Copy that, I'm going to find out and fix it.
