### ISSUE TITLE
Compat with It takes a pillage

### ISSUE THREAD

**Issue by betterworld-sjq** [Viola-Siemens/Villager-Armor-Layer#6]
Illagers in It takes a pillage don't render their armor. Is it the problem of that mod not using specific rendering type?

**Comment by Viola-Siemens** [comment]
Cannot reproduce.

![Archer with Armor](https://github.com/Viola-Siemens/Villager-Armor-Layer/assets/31766783/3a78cae5-1e3a-4e2d-b22c-b233c2179f75)

Command I tried:
```
/summon takesapillage:archer ~ ~ ~
/item replace entity <uuid> armor.<slot> from entity Viola_Siemens weapon.mainhand
```

**Comment by Viola-Siemens** [comment]
> Cannot reproduce.

Minecraft: 1.20.1
Forge: 47.1.0
VAL: 5.0.1
It Takes a Pillage: 1.0.3

**Comment by betterworld-sjq** [comment]
> > Cannot reproduce.
> 
> Minecraft: 1.20.1 Forge: 47.1.0 VAL: 5.0.1 It Takes a Pillage: 1.0.3

It doesn't apply to the Skirmisher. Should I talk to the author of Takesapillage

**Comment by Viola-Siemens** [comment]
> It doesn't apply to the Skirmisher. Should I talk to the author of Takesapillage

https://github.com/izofar/takes-a-pillage/blob/1.18.2/src/main/java/com/izofar/takesapillage/client/renderer/SkirmisherRenderer.java#L16

The Renderer of Skirmisher is not extended from IllagerRenderer, so I think you can report it to takes-a-pillage.

If any other thing I can help with, this issue will be reopened.
