### ISSUE TITLE
Got a crash on startup. If you need more info I can try and help. (1.20.1)

### ISSUE THREAD

**Issue by ThisJustInLocal** [Viola-Siemens/Villager-Armor-Layer#7]
[latest.log](https://github.com/Viola-Siemens/Villager-Armor-Layer/files/14224508/latest.log)

**Comment by Viola-Siemens** [comment]
> Failed to create mod instance. ModID: everycomp, class net.mehvahdjukaar.every_compat.forge.EveryCompatForge

You should probably report this to everycomp.
